### ISSUE TITLE
JException Error

### ISSUE THREAD

**Issue by jimhill10** [jmcameron/attachments#21]
From time to time I see this error in the logs:

```
A PHP Exception occurred on your site. Here you can find the stack trace:
Exception Type: JException
File: /home/USERNAME/public_html/libraries/legacy/error/error.php
Line: 200
Message: ERROR: No function specified! (ERR 0) 
#0 /home/USERNAME/public_html/libraries/legacy/error/error.php(277): JError::raise(1, 500, 'ERROR: No funct...', NULL, true)
#1 /home/USERNAME/public_html/components/com_attachments/controller.php(53): JError::raiseError(500, 'ERROR: No funct...')
#2 /home/USERNAME/public_html/libraries/src/MVC/Controller/BaseController.php(710): AttachmentsController->noop()
#3 /home/USERNAME/public_html/components/com_attachments/attachments.php(41): Joomla\CMS\MVC\Controller\BaseController->execute('downloada0')
#4 /home/USERNAME/public_html/libraries/src/Component/ComponentHelper.php(382): require_once('/home/ USERNAME/...')
#5 /home/ USERNAME/public_html/libraries/src/Component/ComponentHelper.php(357): Joomla\CMS\Component\ComponentHelper::executeComponent('/home/ USERNAME/...')
#6 /home/ USERNAME/public_html/libraries/src/Application/SiteApplication.php(194): Joomla\CMS\Component\ComponentHelper::renderComponent('com_attachments')
#7 /home/ USERNAME/public_html/libraries/src/Application/SiteApplication.php(233): Joomla\CMS\Application\SiteApplication->dispatch()
#8 /home/ USERNAME/public_html/libraries/src/Application/CMSApplication.php(195): Joomla\CMS\Application\SiteApplication->doExecute()
#9 /home/ USERNAME/public_html/index.php(49): Joomla\CMS\Application\CMSApplication->execute()
#10 {main}
Request information
GET variables
Array
(
    [option] => com_attachments
    [task] => download'A=0
    [id] => 6
)
POST variables
Array
(
)
COOKIE variables
Array
(
)
REQUEST variables
Array
(
    [option] => com_attachments
    [task] => download'A=0
    [id] => 6
    [Itemid] => 
)
SERVER variables
Array
(
    [PATH] => /bin:/usr/bin:/usr/local/bin
    [HTTP_ACCEPT] => text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
    [HTTP_ACCEPT_CHARSET] => ISO-8859-1,utf-8;q=0.7,*;q=0.7
    [HTTP_ACCEPT_ENCODING] => gzip
    [HTTP_ACCEPT_LANGUAGE] => en-us,en;q=0.5
    [HTTP_CONNECTION] => Keep-Alive
    [HTTP_HOST] => www.ufcinc.com
    [HTTP_REFERER] => https://www.ufcinc.com/index.php?option=com_attachments&task=download'A=0&id=6
    [HTTP_USER_AGENT] => Mozilla/5.0 (Windows; U; Windows NT 5.1; pt-PT; rv:1.9.1.2) Gecko/20090729 Firefox/3.5.2 (.NET CLR 3.5.30729)
    [DOCUMENT_ROOT] => /home/ USERNAME/public_html
    [REMOTE_ADDR] => 35.236.87.32
    [REMOTE_PORT] => 61380
    [SERVER_ADDR] => 72.249.49.249
    [SERVER_NAME] => www.ufcinc.com
    [SERVER_ADMIN] => webmaster@ufcinc.com
    [SERVER_PORT] => 443
    [REQUEST_URI] => /index.php?option=com_attachments&task=download'A=0&id=6
    [HTTPS] => on
    [HTTP_AUTHORIZATION] => 
    [SSL_PROTOCOL] => TLSv1
    [SSL_SESSION_ID] => 1c1fc54023cf7faf5f32f09c4f91d8b36c516691f4633cb529f9885d6c4135ae
    [SSL_CIPHER] => AES128-SHA
    [SSL_CIPHER_USEKEYSIZE] => 128
    [SSL_CIPHER_ALGKEYSIZE] => 128
    [SCRIPT_FILENAME] => /home/ USERNAME/public_html/index.php
    [QUERY_STRING] => option=com_attachments&task=download'A=0&id=6
    [SCRIPT_URI] => https://www.ufcinc.com/index.php
    [SCRIPT_URL] => /index.php
    [SCRIPT_NAME] => /index.php
    [SERVER_PROTOCOL] => HTTP/1.1
    [SERVER_SOFTWARE] => LiteSpeed
    [REQUEST_METHOD] => GET
    [X-LSCACHE] => on
    [PHP_SELF] => /index.php
    [REQUEST_TIME_FLOAT] => 1534562562.2875
    [REQUEST_TIME] => 1534562562
)
```

**Comment by parapente** [comment]
The problem seems to be with the link: https://www.ufcinc.com/index.php?option=com_attachments&task=download'A=0&id=6 (specifically in the task=download'A=0)

Are you sure that you don't have a wrong link somewhere in your site? You can find the attachment that should have a wrong link using the id. It should be the link with 6 in the table of the attachments. Also it has been a while since the report. Is the issue still valid?

**Comment by parapente** [comment]
Closing this for now as it looks like a database issue. Feel free to reopen if you have more info on the issue.
