### ISSUE TITLE
Blank page in popup after adding file

### ISSUE THREAD

**Issue by fredlang7680** [jmcameron/attachments#41]
Hello, 

We have a bug when we add a file in an article. We click on the button to add file, we choose file, et we click to upload the file. The file is added, no problem.
But when we re-click on he button to add file, we have a blank page in popup:

![image](https://github.com/jmcameron/attachments/assets/56043103/64f1eee0-56c5-4158-af4a-acf437f17e46)

![image](https://github.com/jmcameron/attachments/assets/56043103/e9c0b203-6097-4327-aacb-fda091a8c0d9)

Can you help us please? Thank you a lot

**Comment by parapente** [comment]
Can you please check the browser js console if there are any errors when you add the file? Does it happen in the backend or in the frontend?

**Comment by fredlang7680** [comment]
Hello, 
Thank for your answer.
There's nothing in console
![image](https://github.com/jmcameron/attachments/assets/56043103/5e188775-a7a4-42d4-86c5-e4668ef5ba0f)
the error of jquery appears before uploding file.
It happens in frontend
thanks

**Comment by parapente** [comment]
Please set "log_errors = On" in your php configuration and restart apache/php. Also in Joomla settings, set in the server section error reporting to maximum and in logging to log everything. See if after these settings an error appears when uploading a file in either your screen, apache error.log file or the joomla logs/everything.php file.

**Comment by fredlang7680** [comment]
Hello, thx for your follow-up.
I put "log_errors = On" in PHP.Ini and restart Wamp. But nothing appaers in console. When the blank page appears, there is no network traffic in console.
I also put logging in joomla, I put a file. I saw the logging files, and when I whant to put another file, after the blank page appears, there was nothing else in the joomla's logging. Here's my joomla's logging: 

Everything.php:
2024-04-19T08:54:32+00:00	INFO 163.116.163.121	-	AttachmentsPluginManager loading language...
2024-04-19T08:54:32+00:00	INFO 163.116.163.121	-	AttachmentsPluginManager language loaded: no
2024-04-19T08:54:32+00:00	INFO 163.116.163.121	-	AttachmentsPluginManager loading language...
2024-04-19T08:54:32+00:00	INFO 163.116.163.121	-	AttachmentsPluginManager language loaded: no
2024-04-19T08:54:33+00:00	INFO 163.116.163.121	-	AttachmentsPluginManager loading language...
2024-04-19T08:54:33+00:00	INFO 163.116.163.121	-	AttachmentsPluginManager language loaded: no
2024-04-19T08:54:33+00:00	INFO 163.116.163.121	-	AttachmentsPluginManager loading language...
2024-04-19T08:54:33+00:00	INFO 163.116.163.121	-	AttachmentsPluginManager language loaded: no
2024-04-19T08:54:33+00:00	INFO 163.116.163.121	-	AttachmentsPluginManager loading language...
2024-04-19T08:54:33+00:00	INFO 163.116.163.121	-	AttachmentsPluginManager language loaded: no
2024-04-19T08:54:33+00:00	INFO 163.116.163.121	-	AttachmentsPluginManager loading language...
2024-04-19T08:54:33+00:00	INFO 163.116.163.121	-	AttachmentsPluginManager language loaded: no
2024-04-19T08:54:35+00:00	CRITICAL 163.116.163.121	error	Uncaught Throwable of type Joomla\CMS\Router\Exception\RouteNotFoundException thrown with message "Page introuvable". Stack trace: #0 [ROOT]\libraries\src\Application\SiteApplication.php(746): Joomla\CMS\Router\Router->parse(Object(Joomla\CMS\Uri\Uri), true)
#1 [ROOT]\libraries\src\Application\SiteApplication.php(232): Joomla\CMS\Application\SiteApplication->route()
#2 [ROOT]\libraries\src\Application\CMSApplication.php(293): Joomla\CMS\Application\SiteApplication->doExecute()
#3 [ROOT]\includes\app.php(61): Joomla\CMS\Application\CMSApplication->execute()
#4 [ROOT]\index.php(32): require_once('D:\\wamp64\\www\\c...')
#5 {main}
2024-04-19T08:54:35+00:00	CRITICAL 163.116.163.121	error	Uncaught Throwable of type Joomla\CMS\Router\Exception\RouteNotFoundException thrown with message "Page introuvable". Stack trace: #0 [ROOT]\libraries\src\Application\SiteApplication.php(746): Joomla\CMS\Router\Router->parse(Object(Joomla\CMS\Uri\Uri), true)
#1 [ROOT]\libraries\src\Application\SiteApplication.php(232): Joomla\CMS\Application\SiteApplication->route()
#2 [ROOT]\libraries\src\Application\CMSApplication.php(293): Joomla\CMS\Application\SiteApplication->doExecute()
#3 [ROOT]\includes\app.php(61): Joomla\CMS\Application\CMSApplication->execute()
#4 [ROOT]\index.php(32): require_once('D:\\wamp64\\www\\c...')
#5 {main}
2024-04-19T08:54:35+00:00	CRITICAL 163.116.163.121	error	Uncaught Throwable of type Joomla\CMS\Router\Exception\RouteNotFoundException thrown with message "Page introuvable". Stack trace: #0 [ROOT]\libraries\src\Application\SiteApplication.php(746): Joomla\CMS\Router\Router->parse(Object(Joomla\CMS\Uri\Uri), true)
#1 [ROOT]\libraries\src\Application\SiteApplication.php(232): Joomla\CMS\Application\SiteApplication->route()
#2 [ROOT]\libraries\src\Application\CMSApplication.php(293): Joomla\CMS\Application\SiteApplication->doExecute()
#3 [ROOT]\includes\app.php(61): Joomla\CMS\Application\CMSApplication->execute()
#4 [ROOT]\index.php(32): require_once('D:\\wamp64\\www\\c...')
#5 {main}
2024-04-19T08:54:35+00:00	CRITICAL 163.116.163.121	error	Uncaught Throwable of type Joomla\CMS\Router\Exception\RouteNotFoundException thrown with message "Page introuvable". Stack trace: #0 [ROOT]\libraries\src\Application\SiteApplication.php(746): Joomla\CMS\Router\Router->parse(Object(Joomla\CMS\Uri\Uri), true)
#1 [ROOT]\libraries\src\Application\SiteApplication.php(232): Joomla\CMS\Application\SiteApplication->route()
#2 [ROOT]\libraries\src\Application\CMSApplication.php(293): Joomla\CMS\Application\SiteApplication->doExecute()
#3 [ROOT]\includes\app.php(61): Joomla\CMS\Application\CMSApplication->execute()
#4 [ROOT]\index.php(32): require_once('D:\\wamp64\\www\\c...')
#5 {main}
2024-04-19T08:54:36+00:00	CRITICAL 163.116.163.121	error	Uncaught Throwable of type Joomla\CMS\Router\Exception\RouteNotFoundException thrown with message "Page introuvable". Stack trace: #0 [ROOT]\libraries\src\Application\SiteApplication.php(746): Joomla\CMS\Router\Router->parse(Object(Joomla\CMS\Uri\Uri), true)
#1 [ROOT]\libraries\src\Application\SiteApplication.php(232): Joomla\CMS\Application\SiteApplication->route()
#2 [ROOT]\libraries\src\Application\CMSApplication.php(293): Joomla\CMS\Application\SiteApplication->doExecute()
#3 [ROOT]\includes\app.php(61): Joomla\CMS\Application\CMSApplication->execute()
#4 [ROOT]\index.php(32): require_once('D:\\wamp64\\www\\c...')
#5 {main}
2024-04-19T08:54:36+00:00	INFO 163.116.163.121	-	AttachmentsPluginManager loading language...
2024-04-19T08:54:36+00:00	INFO 163.116.163.121	-	AttachmentsPluginManager language loaded: no
2024-04-19T08:54:36+00:00	INFO 163.116.163.121	-	AttachmentsPluginManager loading language...
2024-04-19T08:54:36+00:00	INFO 163.116.163.121	-	AttachmentsPluginManager language loaded: no
2024-04-19T08:54:51+00:00	INFO 163.116.163.121	-	AttachmentsPluginManager loading language...
2024-04-19T08:54:51+00:00	INFO 163.116.163.121	-	AttachmentsPluginManager language loaded: no
2024-04-19T08:54:51+00:00	INFO 163.116.163.121	-	AttachmentsPluginManager loading language...
2024-04-19T08:54:51+00:00	INFO 163.116.163.121	-	AttachmentsPluginManager language loaded: no
2024-04-19T09:01:36+00:00	INFO 163.116.163.121	-	AttachmentsPluginManager loading language...
2024-04-19T09:01:36+00:00	INFO 163.116.163.121	-	AttachmentsPluginManager language loaded: no
2024-04-19T09:01:38+00:00	INFO 163.116.163.121	-	AttachmentsPluginManager loading language...
2024-04-19T09:01:38+00:00	INFO 163.116.163.121	-	AttachmentsPluginManager language loaded: no
2024-04-19T09:01:38+00:00	INFO 163.116.163.121	-	AttachmentsPluginManager loading language...
2024-04-19T09:01:38+00:00	INFO 163.116.163.121	-	AttachmentsPluginManager language loaded: no
2024-04-19T09:01:39+00:00	INFO 163.116.163.121	-	AttachmentsPluginManager loading language...
2024-04-19T09:01:39+00:00	INFO 163.116.163.121	-	AttachmentsPluginManager language loaded: no
2024-04-19T09:01:39+00:00	INFO 163.116.163.121	-	AttachmentsPluginManager loading language...
2024-04-19T09:01:39+00:00	INFO 163.116.163.121	-	AttachmentsPluginManager language loaded: no
2024-04-19T09:01:39+00:00	INFO 163.116.163.121	-	AttachmentsPluginManager loading language...
2024-04-19T09:01:39+00:00	INFO 163.116.163.121	-	AttachmentsPluginManager language loaded: no
2024-04-19T09:01:39+00:00	INFO 163.116.163.121	-	AttachmentsPluginManager loading language...
2024-04-19T09:01:39+00:00	INFO 163.116.163.121	-	AttachmentsPluginManager language loaded: no
2024-04-19T09:01:40+00:00	INFO 163.116.163.121	-	AttachmentsPluginManager loading language...
2024-04-19T09:01:40+00:00	INFO 163.116.163.121	-	AttachmentsPluginManager language loaded: no
2024-04-19T09:01:54+00:00	INFO 163.116.163.121	-	AttachmentsPluginManager loading language...
2024-04-19T09:01:54+00:00	INFO 163.116.163.121	-	AttachmentsPluginManager language loaded: no
2024-04-19T09:01:55+00:00	INFO 163.116.163.121	-	AttachmentsPluginManager loading language...
2024-04-19T09:01:55+00:00	INFO 163.116.163.121	-	AttachmentsPluginManager language loaded: no
2024-04-19T09:02:06+00:00	INFO 163.116.163.121	-	AttachmentsPluginManager loading language...
2024-04-19T09:02:06+00:00	INFO 163.116.163.121	-	AttachmentsPluginManager language loaded: no
2024-04-19T09:02:07+00:00	INFO 163.116.163.121	-	AttachmentsPluginManager loading language...
2024-04-19T09:02:07+00:00	INFO 163.116.163.121	-	AttachmentsPluginManager language loaded: no

I Uploaded first file at 9:01, and second file (with blank page) just after

Nothing in the error.php

Thanks a lot

**Comment by parapente** [comment]
When you add "log_errors = On" you will get possible errors in "D:/wamp64/logs/php_error.log". I will try to see if I can detect the problem but it would be helpful if we could get an error message to pinpoint the specific part of the code that is at fault.

**Comment by JLTRY** [comment]
Can you provide your browser and your joomla version Thks

**Comment by fredlang7680** [comment]
Joomla : 4.4.3
Chrome : Version 123.0.6312.122 (Build officiel) (64 bits)
Firefox : 115.7.0esr (32 bits)
If you want, we can do a teams visio and you can take control to see in more details
Thks

**Comment by JLTRY** [comment]
Hello I reproduced it with firefox and joomla 4
I will try to debug it with Xdebug

**Comment by fredlang7680** [comment]
TOP! Thank you very much!

**Comment by JLTRY** [comment]
I have corrected it with pull request [pull/46](https://github.com/jmcameron/attachments/pull/46l)

**Comment by JLTRY** [comment]
@fredlang7680 can you try it

**Comment by fredlang7680** [comment]
Perfect! thank you very much!
I didnt know how to pull the new files, then in my dev server I updated lines in each file with your commit. 
Just a little thing: when I close the popup, the new files are not shown. I have to do F5 to show the files. 
anyway, if you can't change this, my coworkers are going to gain time.
You will update the extension with the new updates, or I have to update the lines in production server?
Thank you again!

**Comment by parapente** [comment]
@fredlang7680 fixed in #48 which is now merged to master.

**Comment by JLTRY** [comment]
@fredlang7680 I provided a new release https://github.com/jmcameron/attachments/releases/tag/v4.0.1
with the correction inside
